- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  vars:
    minikube_package_name: minikube_latest_amd64
    minikube_package_url: 'https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb'
  tasks:

    - name: Install packages
      apt:
        name:
        - podman-docker
        - docker-compose
        - jq
        - maven
        - openjdk-11-jdk-headless
        - python3-pip

    - name: Remove packages for security compliance
      apt:
        name:
        - nis
        - rsh-server
        - telnetd
        state: absent
        autoremove: yes

    - name: Check if minikube is installed
      command: dpkg-query -W minikube
      register: minikube_package_check_deb
      failed_when: minikube_package_check_deb.rc > 1
      changed_when: minikube_package_check_deb.rc == 1
    - name: Download minikube
      get_url:
        url="{{ minikube_package_url }}"
        dest="/root/{{ minikube_package_name }}.deb"
      when: minikube_package_check_deb.rc == 1
    - name: Install minikube
      apt: deb="/root/{{ minikube_package_name }}.deb"
      when: minikube_package_check_deb.rc == 1

    - name: Determine available groups
      getent:
        database: group
